version: 0.2
env:
  variables:
    AWS_ACCOUNT_ID: "899864473854"
    IMAGE_REPO_NAME: "ci-test/test-app"
  secrets-manager:
    GITHUB_SSH_KEY: "github/ssh-key"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo check files from ~/.ssh
      - ls -l ~/.ssh
      - echo Parsing the SSH key..
      - echo GITHUB_SSH_KEY $GITHUB_SSH_KEY
      - echo $GITHUB_SSH_KEY > ~/.ssh/id_rsa
      - chmod 400 ~/.ssh/id_rsa
      - cat ~/.ssh/id_rsa
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - export IMAGE_TAG=$(python -c 'import app; print(app.__version__)')
      - echo "IMAGE_REPO_NAME ${IMAGE_REPO_NAME}"
      - echo "IMAGE_TAG       ${IMAGE_TAG}"
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
