version: 0.2
env:
  variables:
    AWS_ACCOUNT_ID: "899864473854"
    IMAGE_REPO_NAME: "ci-test/test-app"
  secrets-manager:
    GITHUB_SSH_ID_RSA: "github/ssh-key/id_rsa"
    GITHUB_SSH_ID_RSA_PUB: "github/ssh-key/id-rsa-pub"

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y jq
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo check files from ~/.ssh
      - ls -l ~/.ssh
      - echo Parsing the SSH key..
      - env | sort
      - echo GITHUB_SSH_KEY $GITHUB_SSH_KEY
      - echo $GITHUB_SSH_ID_RSA > ~/.ssh/id_rsa
      - echo $GITHUB_SSH_ID_RSA_PUB > ~/.ssh/id_rsa.pub
      - chmod 400 ~/.ssh/id_rsa ~/.ssh/id_rsa.pub
      - ls -l ~/.ssh
      - echo 'id_rsa'
      - cat ~/.ssh/id_rsa
      - echo 'id_rsa.pub'
      - cat ~/.ssh/id_rsa.pub
      - ssh -T git@github.com
      - git clone git@github.com:purple-lion/test-app-ops.git /opt/test-app-ops
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - export IMAGE_TAG=$(python -c 'import app; print(app.__version__)')
      - echo "IMAGE_REPO_NAME ${IMAGE_REPO_NAME}"
      - echo "IMAGE_TAG       ${IMAGE_TAG}"
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Update change to test-app-ops
      - cd /opt/test-app-ops
      - echo $IMAGE_TAG > VERSION.txt
      - git add VERSION.txt
      - git commit -m "Bump version to $IMAGE_TAG" --author "CodeBuild <pyunghyuk@likelion.net>"
      - git push origin master
